### PR TITLE
Add "container" class to style the entire block

### PR DESCRIPTION
**Pull request by bubuku**

### CODE REVIEW

**Comment by mtoensing** [comment]
There is no need to add a static div with a class in the code from my point of view. You can add a class in Gutenberg directly without additional code. Put simpletoc in a reusable block, and you have a static class. I know that this would make some things easier. But I would like to keep it simple. And if I made this an option within SimpleToc itself, the reusable block solution would be obsolete. Comments?

**Comment by bubuku** [comment]
You're absolutely right, I hadn't thought of that option, it was because everything was grouped together.

What would be nice is to be able to change the title in case you need to change it on different pages or Custom Post Type, or don't you see it necessary?

**Comment by mtoensing** [comment]
You can change the title by removing it and add a custom h2 block

**Comment by bubuku** [comment]
Ok, you are absolutely right.

I'm not saying anything else anymore, thanks for the plugin, I love it for its simplicity

**Pull request closed without merging**
